### ISSUE TITLE
Add JS Fiddle and resolve using undefined function on array

### ISSUE THREAD

**Issue by mantas-done** [csga5000/tinymce-prevent-delete#1]
also
return [8, 9, 13, 46].contains(c)
code, throws exception for me (i am using more plugins)

**Comment by csga5000** [comment]
Sorry for delay.  But resolved.

**Comment by csga5000** [comment]
My dumb, I have some array prototypes I tend to assign in my personal projects, and I was using one.  If i'd written this originally with the intent of a library, I would have just made it a function.

The fiddle can be found in the readme.
