### ISSUE TITLE
Stability

### ISSUE THREAD

**Issue by fgabrieli** [csga5000/tinymce-prevent-delete#7]
First of all, thank you very much to publish this plugin so we all can use it. I would like to know, in a scale from 1 to 10, how stable do you think this plugin is today for production use? 

thanks :-)
Fernando

**Comment by csga5000** [comment]
I'd test and see for yourself.  It's ok.  I have a client using it with perhaps a hundred users, it's kind of used by employees.  Unfortunately I haven't seen any good alternatives, so if this isn't up to your standards, feel free to make improvements and submit a pull request.
